type: docker
kind: pipeline
name: default
when:
  branch:
    - main
  event:
    - push

steps:
  - name: build
    image: x1unix/go-mingw:1.17
    commands:
    - curl https://github.com/Flangvik/SharpCollection/raw/master/NetFramework_4.0_Any/Rubeus.exe > internal/execute_assembly/assemblies/rubeus.exe
    - make

image_pull_secrets:
- docker_registry_auth
